### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by dongwangdw** [kubernetes/code-generator#113]
I want to update my controller to new version.
But  I get this error when to produce the code:
```
Generating deepcopy funcs
Generating clientset for mycontroller:v1 at github.com/dongwangdw/mycontroller/pkg/client/clientset
panic: runtime error: index out of range [1] with length 0

goroutine 95 [running]:
golang.org/x/tools/internal/imports.(*ModuleResolver).scanDirForPackage(0xc001580ae0, 0xc005846440, 0x10, 0x4, 0xc006d518c0, 0x47, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/imports/mod.go:346 +0x990
golang.org/x/tools/internal/imports.(*ModuleResolver).scan.func1(0xc005846440, 0x10, 0x4, 0xc006d518c0, 0x47)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/imports/mod.go:263 +0x73e
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc008f3e100, 0xc006d518c0, 0x52, 0x0, 0xc006d518c0, 0x52)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/gopathwalk/walk.go:175 +0xf3
golang.org/x/tools/internal/fastwalk.(*walker).onDirEnt(0xc008278060, 0xc00691a5a0, 0x47, 0xc0052d11c0, 0xa, 0x0, 0x0, 0xc0058c9de0)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk.go:168 +0xbb
golang.org/x/tools/internal/fastwalk.readDir(0xc00691a5a0, 0x47, 0xc0058cbe50, 0x0, 0x0)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk_unix.go:68 +0x228
golang.org/x/tools/internal/fastwalk.(*walker).walk(0xc008278060, 0xc00691a5a0, 0x47, 0x1, 0x1, 0x0)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk.go:195 +0x6a
golang.org/x/tools/internal/fastwalk.(*walker).doWork(0xc008278060, 0xc0059c8bf0)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk.go:134 +0x175
created by golang.org/x/tools/internal/fastwalk.Walk
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk.go:81 +0x248```

**Comment by dongwangdw** [comment]
The go.mod file is :

```
go 1.13

replace k8s.io/client-go v12.0.0+incompatible => k8s.io/client-go v0.18.2

require (
	github.com/coreos/prometheus-operator v0.40.0
	github.com/sirupsen/logrus v1.6.0
	k8s.io/api v0.18.5
	k8s.io/apimachinery v0.18.5
	k8s.io/client-go v12.0.0+incompatible
	k8s.io/code-generator v0.18.5
)```

**Comment by dongwangdw** [comment]
At least, I need to know what is going on here. Version incompatible?

**Comment by Jeffwan** [comment]
I meet this problem as well

/reopen

**Comment by Jeffwan** [comment]
@dongwangdw Do you use golang 1.13?
