### ISSUE TITLE
release1.8 client-gen doesn't accept --go-header or -o flags

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/code-generator#13]

**Comment by ash2k** [comment]
This is still an issue, isn't it? The option is no longer accepted so if it is provided, it fails with:
```console
client-gen \
        --input-base "github.com/atlassian/smith/pkg/apis/" \
        --input "smith/v1" \
        --clientset-path "github.com/atlassian/smith/pkg/client/clientset_generated/" \
        --clientset-name "clientset" \
        --go-header-file "build/code-generator/boilerplate.go.txt"
unknown flag: --go-header-file
Usage of bazel-bin/vendor/k8s.io/code-generator/cmd/client-gen/client-gen:
      --alsologtostderr                        log to standard error as well as files
      --clientset-api-path string              the value of default API path.
  -n, --clientset-name string                  the name of the generated clientset package. (default "internalclientset")
      --clientset-only                         when set, client-gen only generates the clientset shell, without generating the individual typed clients
      --clientset-path string                  the generated clientset will be output to <clientset-path>/<clientset-name>. (default "k8s.io/kubernetes/pkg/client/clientset_generated/")
      --fake-clientset                         when set, client-gen will generate the fake clientset that can be used in tests (default true)
      --included-types-overrides stringSlice   list of group/version/type for which client should be generated. By default, client is generated for all types which have genclient in types.go. This overrides that. For each groupVersion in this list, only the types mentioned here will be included. The default check of genclient will be used for other group versions.
      --input stringSlice                      group/versions that client-gen will generate clients for. At most one version per group is allowed. Specified in the format "group1/version1,group2/version2...". (default [api/,admissionregistration/,authentication/,authorization/,autoscaling/,batch/,certificates/,extensions/,rbac/,storage/,apps/,policy/,scheduling/,settings/,networking/])
      --input-base string                      base path to look for the api group. (default "k8s.io/kubernetes/pkg/apis")
      --log_backtrace_at traceLocation         when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                         If non-empty, write log files in this directory
      --logtostderr                            log to standard error instead of files
      --stderrthreshold severity               logs at or above this threshold go to stderr (default 2)
  -v, --v Level                                log level for V logs
      --vmodule moduleSpec                     comma-separated list of pattern=N settings for file-filtered logging
```
If it is omitted it fails with:
```console
client-gen \
        --input-base "github.com/atlassian/smith/pkg/apis/" \
        --input "smith/v1" \
        --clientset-path "github.com/atlassian/smith/pkg/client/clientset_generated/" \
        --clientset-name "clientset"
ERROR: logging before flag.Parse: F1029 15:02:19.799179    8461 client_generator.go:312] Failed loading boilerplate: open /Users/ash2k/gopath/src/k8s.io/kubernetes/hack/boilerplate/boilerplate.go.txt: no such file or directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc42000e000, 0xc42a548900, 0xc1, 0x109)
        vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/golang/glog.(*loggingT).output(0x148ffa0, 0xc400000003, 0xc42a8a3a20, 0x146030e, 0x13, 0x138, 0x0)
        vendor/github.com/golang/glog/glog.go:720 +0x345
github.com/golang/glog.(*loggingT).printf(0x148ffa0, 0xc400000003, 0x1306ffd, 0x1e, 0xc42b05d928, 0x1, 0x1)
        vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/golang/glog.Fatalf(0x1306ffd, 0x1e, 0xc42b05d928, 0x1, 0x1)
        vendor/github.com/golang/glog/glog.go:1148 +0x67
k8s.io/code-generator/cmd/client-gen/generators.Packages(0xc425d97f20, 0xc420010240, 0x12ff74b, 0x6, 0xc425d97f20)
        vendor/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go:312 +0xdf
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc420010240, 0xc42007ef00, 0x12ff74b, 0x6, 0x13151b8, 0x1, 0x4)
        vendor/k8s.io/gengo/args/args.go:176 +0x1d4
main.main()
        vendor/k8s.io/code-generator/cmd/client-gen/main.go:199 +0x65e
make: *** [generate-client] Error 255
```
That means the latest gengo revision 70ad626ed2d7a483d89d2c4c56364d60b48ee8fc is unuseable outside of k/k repo. Am I missing something?

The behaviour has changed after https://github.com/kubernetes/gengo/pull/80 - commit before the merge works fine.

/cc @sttts

**Comment by sttts** [comment]
@ash2k not sure I can follow you. If you use the gengo we have in Godeps.json (70ad626ed2d7a483d89d2c4c56364d60b48ee8fc) it works. We never claim that our code works with master of dependencies. Here we are (un)lucky that compilation breaks. In the worst case our release branches will not even compile with master of the dependencies.

**Comment by ash2k** [comment]
@sttts sure, that's fine. My comment was more to let you know in advance that things are not working.
