### ISSUE TITLE
glog doesn't like it when non-standard flag package is used

### ISSUE THREAD

**Issue by ash2k** [kubernetes/code-generator#16]
Note the `ERROR: logging before flag.Parse`:
```console
client-gen \
>         --input-base "github.com/atlassian/smith/pkg/apis/" \
>         --input "smith/v1" \
>         --clientset-path "github.com/atlassian/smith/pkg/client/clientset_generated/" \
>         --clientset-name "clientset"

ERROR: logging before flag.Parse: F1029 14:26:52.019063   88249 client_generator.go:312] Failed loading boilerplate: open /Users/ash2k/gopath/src/k8s.io/kubernetes/hack/boilerplate/boilerplate.go.txt: no such file or directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc42000e000, 0xc4264e8c60, 0xc1, 0x109)
        vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/golang/glog.(*loggingT).output(0x148ffa0, 0xc400000003, 0xc4253b5ce0, 0x146030e, 0x13, 0x138, 0x0)
        vendor/github.com/golang/glog/glog.go:720 +0x345
github.com/golang/glog.(*loggingT).printf(0x148ffa0, 0xc400000003, 0x1306ffd, 0x1e, 0xc42ad21928, 0x1, 0x1)
        vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/golang/glog.Fatalf(0x1306ffd, 0x1e, 0xc42ad21928, 0x1, 0x1)
        vendor/github.com/golang/glog/glog.go:1148 +0x67
k8s.io/code-generator/cmd/client-gen/generators.Packages(0xc424dfc2a0, 0xc420010240, 0x12ff74b, 0x6, 0xc424dfc2a0)
        vendor/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go:312 +0xdf
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc420010240, 0xc420080f00, 0x12ff74b, 0x6, 0x13151b8, 0x1, 0x4)
        vendor/k8s.io/gengo/args/args.go:176 +0x1d4
main.main()
        vendor/k8s.io/code-generator/cmd/client-gen/main.go:199 +0x65e
```

**Comment by frankgreco** [comment]
I just encountered this as well 

/remove-lifecycle stale

**Comment by nikhita** [comment]
@ash2k Is this still relevant with klog?

**Comment by ash2k** [comment]
I haven't tested but I guess it is not. Worth testing before closing I think. I haven't updated all our stuff to use 1.13/klog libraries - this is in progress. Once we are there, I can see it this issue still exists.
